source "https://rubygems.org"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", ">= 1.1.0", require: false
gem "bcrypt", "~> 3.1.7"
gem "devise", "~> 4.9"
gem "devise-security", "~> 0.18"
gem "jwt", "~> 2.8"
gem "rack-cors"
gem "aws-sdk-s3", "~> 1.146"
gem "rubyzip", "~> 2.3"
gem "sidekiq", "~> 6.5"
gem "redis", "~> 4.0"
gem "jbuilder"

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.4"
end

group :development do
  gem "listen", "~> 3.8"
  gem "pry"
end
