source "https://rubygems.org"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.8"
gem "rack-cors"
gem "aws-sdk-s3", "~> 1.146"
gem "rubyzip", "~> 2.3"
gem "sidekiq", "~> 7.2"
gem "redis", "~> 5.0"
gem "jbuilder"

group :development, :test do
  gem "debug", platforms: %i[mri]
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem "listen", "~> 3.8"
  gem "pry"
end
